const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: '1.5',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 140,
      brand: 'Adidas',
      rating: '1',
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Oxford Slim Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 100,
      brand: 'Oxford',
      rating: '4.4',
      numReviews: 7,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Adidas Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 130,
      brand: 'Adidas',
      rating: '3.9',
      numReviews: 5,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 160,
      brand: 'Nike',
      rating: '3.7',
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Oxford Slim Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 190,
      brand: 'Oxford',
      rating: '3.5',
      numReviews: 6,
      description: 'high quality product',
    },
  ],
};

export default data;
